// <auto-generated />
using System;
using GraphQL_EF5Core_API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GraphQL_EF5Core_API.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GraphQL_EF5Core_API.Skuirrel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skuirrel");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f5ccccf-ec37-4e5e-8763-fd42088bd6b2"),
                            Age = 10,
                            Location = "The Trees",
                            Name = "Alan Korn"
                        },
                        new
                        {
                            Id = new Guid("860a7e27-8b5f-4b04-9a67-008000b6bfe1"),
                            Age = 5,
                            Location = "The Oak",
                            Name = "Savannah Korn"
                        },
                        new
                        {
                            Id = new Guid("48569a5a-d01f-456b-9a64-f608714ca491"),
                            Age = 9,
                            Location = "The Pine",
                            Name = "Sienna Korn"
                        },
                        new
                        {
                            Id = new Guid("f1aa9f34-609d-485b-9777-b5dd99343a13"),
                            Age = 11,
                            Location = "The Tree House",
                            Name = "Mamma Korn"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
